<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25536" started-at="2020-07-01T16:20:40Z" finished-at="2020-07-01T16:21:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25536" started-at="2020-07-01T16:20:40Z" finished-at="2020-07-01T16:21:05Z">
      <class name="com.pyaranbee.tests.TVsAndAppliancesPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.pyaranbee.tests.TVsAndAppliancesPageTest@1bd4fdd]" name="setUp" is-config="true" duration-ms="24929" started-at="2020-07-01T16:20:40Z" finished-at="2020-07-01T16:21:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verify_popUp_Close()[pri:0, instance:com.pyaranbee.tests.TVsAndAppliancesPageTest@1bd4fdd]" name="verify_popUp_Close" duration-ms="557" started-at="2020-07-01T16:21:05Z" finished-at="2020-07-01T16:21:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_popUp_Close -->
        <test-method status="FAIL" signature="verify_TVsAndAppliances_Tab()[pri:1, instance:com.pyaranbee.tests.TVsAndAppliancesPageTest@1bd4fdd]" name="verify_TVsAndAppliances_Tab" duration-ms="7" started-at="2020-07-01T16:21:05Z" finished-at="2020-07-01T16:21:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[washingmachine option is not visible expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: washingmachine option is not visible expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.pyaranbee.tests.TVsAndAppliancesPageTest.verify_TVsAndAppliances_Tab(TVsAndAppliancesPageTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_TVsAndAppliances_Tab -->
      </class> <!-- com.pyaranbee.tests.TVsAndAppliancesPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
